spring.application.name=theatre-ticketing-system
spring.profiles.active=dev

theatre.reservation-hold-minutes=15
theatre.default-page-size=10

logging.level.root=WARN
logging.level.bg.uni.fmi.theatre=INFO
logging.file.name=logs/theatre.log
logging.level.org.liquibase=INFO

spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/theatre?currentSchema=theatre
spring.datasource.username=${DS_USERNAME}
spring.datasource.password=${DS_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=theatre
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.default-schema=theatre
