logging.file.name=logs/theatre-test.log
logging.level.root=WARN
logging.level.bg.uni.fmi.theatre=ERROR

spring.datasource.url=jdbc:h2:mem:theatre_test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS THEATRE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.default_schema=theatre

spring.liquibase.enabled=false

spring.ai.openai.api-key=test-key
